Repository OpenLab-dev/shopped, pull requests merged in 2024-03, with the labels that each got.

#2 build: remove pnpm-lock unnecessary
  packages/dashboard/pnpm-lock.yaml
  packages/ui/package.json
  packages/ui/pnpm-lock.yaml
  pnpm-lock.yaml
Labels: bug

#8 chore: refactor folder an files utilities
  .npmrc
  packages/dashboard/src/components/LateralMenu.tsx
  packages/dashboard/src/lib/const.ts
  packages/ui/src/app/about/page.tsx
  packages/ui/src/app/contact/page.tsx
  packages/ui/src/components/carousel-iphones.tsx
  packages/ui/src/components/categories-section.tsx
  packages/ui/src/components/categories.tsx
  packages/ui/src/components/navbar.tsx
  packages/ui/src/components/watch-carosel.tsx
  packages/ui/src/lib/const.ts
Labels: Tools

#19 fix: update lateralmenu and unocss styles
  packages/dashboard/src/components/LateralMenu.tsx
  packages/dashboard/src/lib/const.ts
  packages/dashboard/unocss.config.ts
Labels: Design, Fix

#21 fix: update side menu styles
  packages/dashboard/index.html
  packages/dashboard/src/components/LateralMenu.tsx
Labels: Design, Fix

#22 fix: remove tank Stack Dev tools in production (#11)
  packages/dashboard/src/components/ReactLazy.ts
  packages/dashboard/src/routes/__root.tsx
Labels: Bug, Tools
