Repository OpenLab-dev/shopped, pull requests merged in 2024-04, with the labels that each got.

#73 feat(api): add new function for delete product (#48)
  api/routers/v1/products.py
  api/services/products.py
  commerce.sqlite
Labels: Server, Feature

#82 feat(api): add new function for edit product (#47)
  api/deps.py
  api/routers/v1/categories.py
  api/routers/v1/products.py
  api/services/categories.py
  api/services/products.py
  commerce.sqlite
Labels: Server, Feature

#106 fix(dashboard): new design for login (#31)
  packages/dashboard/src/routes/login.tsx
Labels: Design, Feature, Dashboard

#122 feat(api): added new function get users (#107)
  api/bcrypt.py
  api/db/conn.py
  api/db/test_conn.py
  api/deps.py
  api/env.py
  api/helpers/http.py
  api/main.py
  api/routers/api.py
  api/routers/v1/categories.py
  api/routers/v1/products.py
  api/routers/v1/test_categories.py
  api/routers/v1/test_products.py
  api/routers/v1/users.py
  api/schemas/models.py
  api/schemas/types.py
  api/services/auth.py
  api/services/categories.py
  api/services/products.py
  api/test_bcrypt.py
  commerce.sqlite
Labels: Server, Feature

#128 fix(api): add enviroment variable
  api/db/conn.py
Labels: Bug, Fix

#129 feat(api): permission was added for the vite url
  api/main.py
Labels: Server

#145 feat(ui): form was added to login and register in a modal
  packages/ui/src/components/login-register.tsx
  packages/ui/src/components/user-nav.tsx
Labels: Design, Feature, Ui

#146 build(ui, dashboard): library @ openui-org/react was updated
  packages/dashboard/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: Dashboard, Ui

#147 fix(ui): fix styles in loginregister and usernav
  packages/ui/src/components/login-register.tsx
  packages/ui/src/components/login.tsx
  packages/ui/src/components/register.tsx
  packages/ui/src/components/user-nav.tsx
Labels: Design, Fix, Ui

#150 feat(dashboard): added the route and category table
  packages/dashboard/src/components/pages/categories/get.tsx
  packages/dashboard/src/components/pages/categories/index.tsx
  packages/dashboard/src/components/tables/categories/categories-table.tsx
  packages/dashboard/src/components/tables/categories/cell-action.tsx
  packages/dashboard/src/components/tables/categories/columns.tsx
  packages/dashboard/src/components/utils/data-table.tsx
  packages/dashboard/src/lib/mocks.ts
  packages/dashboard/src/routeTree.gen.ts
  packages/dashboard/src/routes/categories/index.tsx
  packages/dashboard/src/routes/categories/new.tsx
Labels: Design, Feature, Dashboard

#168 fix(api): password is no longer sent at login
  api/routers/v1/users.py
Labels: Server, Fix

#170 feat(dashboard): page for create categories
  packages/dashboard/src/components/pages/categories/create-category.tsx
  pnpm-lock.yaml
Labels: Design, Feature, Dashboard

#176 feat(dashboard): added the form for create products
  packages/dashboard/src/components/pages/products/create-product.tsx
Labels: Design, Feature, Dashboard

#180 feat(ui): add view-transition
  .vscode/settings.json
  packages/ui/package.json
  packages/ui/src/app/layout.tsx
  packages/ui/src/components/footer.tsx
  packages/ui/src/components/header.tsx
  pnpm-lock.yaml
Labels: Feature, Ui

#182 feat(ui): product preview has been added
  packages/ui/src/app/products/[name]/page.tsx
  packages/ui/src/components/product-account.tsx
  packages/ui/src/components/product.tsx
  pnpm-lock.yaml
Labels: Design, Feature, Ui

#183 feat(dashboard): added new route called orders
  packages/dashboard/src/components/pages/orders/order.tsx
  packages/dashboard/src/components/tables/orders/cell-actions.tsx
  packages/dashboard/src/components/tables/orders/columns.tsx
  packages/dashboard/src/components/tables/orders/orders-table.tsx
  packages/dashboard/src/lib/mocks.ts
  packages/dashboard/src/routes/index.tsx
  packages/dashboard/types/index.d.ts
  packages/ui/src/app/products/page.tsx
Labels: Design, Feature, Dashboard

#184 feat(ui): added carousel for products
  packages/ui/src/app/page.tsx
  packages/ui/src/components/carousel.tsx
Labels: Design, Feature, Ui

#185 feat(ui): banner section added
  packages/ui/public/banner2.webp
  packages/ui/src/app/page.tsx
  packages/ui/src/components/banners-second.tsx
Labels: Design, Feature, Ui

#186 fix(ui): styles corrected for the mobile version
  packages/ui/src/components/banners-second.tsx
  packages/ui/src/components/banners.tsx
  packages/ui/src/components/hero-video.tsx
Labels: Design, Fix, Ui

#187 feat(dashboard): new component call `Input-File`
  packages/dashboard/src/components/pages/categories/create-category.tsx
  packages/dashboard/src/components/pages/products/create-product.tsx
  packages/dashboard/src/components/utils/input-file.tsx
Labels: Design, Feature, Dashboard

#188 feat(ui): card animation for movile
  packages/ui/src/components/product.tsx
Labels: Design, Feature, Ui
